spark.jars=/Users/mac/Documents/modern-data-warehouse/jars/iceberg-spark-runtime-3.5_2.12-1.6.0.jar,/Users/mac/Documents/modern-data-warehouse/jars/iceberg-aws-bundle-1.6.0.jar

spark.sql.extensions=org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions
spark.sql.catalog.warehouse=org.apache.iceberg.spark.SparkCatalog
spark.sql.catalog.warehouse.type=rest
spark.sql.catalog.warehouse.uri=http://localhost:8181

spark.sql.catalog.warehouse.s3.endpoint=http://localhost:9000
spark.sql.catalog.warehouse.s3.path-style-access=true
spark.sql.catalog.warehouse.s3.region=us-east-1

spark.hadoop.fs.s3a.endpoint.region=us-east-1

spark.driver.extraJavaOptions=-Daws.region=us-east-1 -Daws.accessKeyId=minioadmin -Daws.secretAccessKey=minioadmin123
spark.executor.extraJavaOptions=-Daws.region=us-east-1 -Daws.accessKeyId=minioadmin -Daws.secretAccessKey=minioadmin123
spark.sql.cli.print.header=true